version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb-blog
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tpmongo
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-net

networks:
  blog-net:
    driver: bridge

volumes:
  mongo_data: