version: '3.8'

services:
  db:
    image: postgres:12.10  # Puedes usar 'postgres:latest' si no necesitas una versión específica
    container_name: db2-tp5
    environment:
      POSTGRES_USER: postgres  # Usuario de la base de datos
      POSTGRES_PASSWORD: admin   # Contraseña para el usuario
      POSTGRES_DB: db2tp5 # Nombre de la base de datos inicial
    ports:
      - "5002:5432"  # Mapea el puerto 5432 del contenedor al puerto 5002 del host
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volumen para persistencia de datos
    networks:
      - productos_net  # Red para la comunicación entre contenedores

  redis:
    image: redis:latest
    container_name: redis-tp5
    ports:
      - "6379:6379"
    networks:
      - productos_net


volumes:
  pgdata:  # Definición del volumen persistente

networks:
  productos_net:
    driver: bridge  # Configura la red en modo bridge