spring:
  datasource:
    url: jdbc:postgresql://localhost:5002/db2tp5
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG

server:
  port: 8080